### ISSUE TITLE
All pods not showing up in the API (or influx/grafana backend)

### ISSUE THREAD

**Issue by ApsOps** [kubernetes/heapster#1182]
I just noticed that some of the pods were not showing up in heapster metrics API. No idea why.
I deleted and recreated the deployment and it showed up.

I have another such deployment, for which, heapster isn’t showing any pods at
```curl http://{{ MASTER }}/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/model/namespaces/default/pods/```

Is this known behavior? How can I debug this?

**Comment by DirectXMan12** [comment]
Hmm... do the pods appear eventually, or do they just never appear?  You could try running at a high-verbosity log level (e.g. 6), which should show you more of what's going on under the hood, and the requests that kubernetes is making.  Also, can you please report your kubernetes and Heapster versions (if you're running from master on either, indicate the git SHA)

**Comment by ApsOps** [comment]
@DirectXMan12 Thanks for replying :)

Kubernetes version `v1.2.4`
Heapster version `v1.0.2`

It looks like newly created pods show up but go away randomly after some time.

Heapster logs look okay.
```
I0606 17:55:05.000211 1 manager.go:79] Scraping metrics start: 2016-06-06 17:54:00 +0000 UTC, end: 2016-06-06 17:55:00 +0000 UTC
I0606 17:55:05.033620 1 manager.go:152] ScrapeMetrics: time: 33.313006ms size: 59
I0606 17:56:05.000232 1 manager.go:79] Scraping metrics start: 2016-06-06 17:55:00 +0000 UTC, end: 2016-06-06 17:56:00 +0000 UTC
I0606 17:56:05.068257 1 manager.go:152] ScrapeMetrics: time: 67.868802ms size: 59
```
```
I0606 18:04:05.000209       1 manager.go:79] Scraping metrics start: 2016-06-06 18:03:00 +0000 UTC, end: 2016-06-06 18:04:00 +0000 UTC
I0606 18:04:05.006531       1 manager.go:98] Querying source: kubelet_summary:10.0.61.117:10255
I0606 18:04:05.007616       1 manager.go:98] Querying source: kubelet_summary:10.0.100.160:10255
I0606 18:04:05.010843       1 round_trippers.go:286] GET http://10.0.100.160:10255/stats/summary/ 200 OK in 3 milliseconds
I0606 18:04:05.012862       1 round_trippers.go:286] GET http://10.0.61.117:10255/stats/summary/ 200 OK in 6 milliseconds
I0606 18:04:05.014526       1 manager.go:98] Querying source: kubelet_summary:10.0.100.162:10255
I0606 18:04:05.018536       1 manager.go:98] Querying source: kubelet_summary:10.0.100.161:10255
I0606 18:04:05.021347       1 round_trippers.go:286] GET http://10.0.100.161:10255/stats/summary/ 200 OK in 2 milliseconds
I0606 18:04:05.023787       1 round_trippers.go:286] GET http://10.0.100.162:10255/stats/summary/ 200 OK in 9 milliseconds
I0606 18:04:05.029525       1 manager.go:98] Querying source: kubelet_summary:10.0.58.122:10255
I0606 18:04:05.034370       1 round_trippers.go:286] GET http://10.0.58.122:10255/stats/summary/ 200 OK in 4 milliseconds
I0606 18:04:05.035122       1 manager.go:152] ScrapeMetrics: time: 34.746036ms size: 62
I0606 18:04:05.035169       1 manager.go:154]    scrape  bucket 0: 5
I0606 18:04:05.035238       1 manager.go:154]    scrape  bucket 1: 0
I0606 18:04:05.035514       1 manager.go:154]    scrape  bucket 2: 0
I0606 18:04:05.035738       1 manager.go:154]    scrape  bucket 3: 0
I0606 18:04:05.035960       1 manager.go:154]    scrape  bucket 4: 0
I0606 18:04:05.036177       1 manager.go:154]    scrape  bucket 5: 0
I0606 18:04:05.036395       1 manager.go:154]    scrape  bucket 6: 0
I0606 18:04:05.036606       1 manager.go:154]    scrape  bucket 7: 0
I0606 18:04:05.036821       1 manager.go:154]    scrape  bucket 8: 0
I0606 18:04:05.037183       1 manager.go:154]    scrape  bucket 9: 0
I0606 18:04:05.037250       1 manager.go:154]    scrape  bucket 10: 0
I0606 18:04:05.038466       1 manager.go:113] Pushing data to: Metric Sink
I0606 18:04:05.038501       1 manager.go:116] Data push completed: Metric Sink
I0606 18:04:05.038677       1 manager.go:113] Pushing data to: InfluxDB Sink
I0606 18:04:05.038961       1 manager.go:116] Data push completed: InfluxDB Sink
I0606 18:04:05.342816       1 influxdb.go:145] Exported 1138 data to influxDB in 283.752115ms
```

**Comment by DirectXMan12** [comment]
@ApsOps and I discussed further, and it looks like one of his nodes is not reporting any pods at its stats endpoint.

**Comment by ApsOps** [comment]
We found out that pod list not sent by one of the nodes. This node is throwing errors in kubelet logs:
```
I0606 18:31:30.025970    4435 handler.go:239] HTTP InternalServerError: Internal Error: unable to find Docker container "10bfe366a0bcd97dbce295d91c6219303115ef4e41c4c3581896c94201e27b1c"
I0606 18:31:30.026020    4435 server.go:1096] GET /stats/kube-system/heapster-v1.0.2-2856270887-3218g/7796e605-2c11-11e6-aed5-12bca96a847b/heapster: (150.391µs) 500
goroutine 1095016 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc208b761c0, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa6
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc208b761c0, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x32
github.com/emicklei/go-restful.(*Response).WriteHeader(0xc208efaa80, 0x1f4)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:191 +0x48
github.com/emicklei/go-restful.(*Response).WriteErrorString(0xc208efaa80, 0x1f4, 0xc208e5d980, 0x72, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:180 +0x128
k8s.io/kubernetes/pkg/kubelet/server/stats.handleError(0xc208efaa80, 0x7f6a08d4f040, 0xc208c55c00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/handler.go:240 +0x29a
k8s.io/kubernetes/pkg/kubelet/server/stats.(*handler).handlePodContainer(0xc2083c0d80, 0xc2090a9110, 0xc208efaa80)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/handler.go:216 +0x8a6
k8s.io/kubernetes/pkg/kubelet/server/stats.*handler.(k8s.io/kubernetes/pkg/kubelet/server/stats.handlePodContainer)·fm(0xc2090a9110, 0xc208efaa80)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/handler.go:72 +0x3b
github.com/emicklei/go-restful.(*Container).dispatch(0xc2083757a0, 0x7f6a08d7c788, 0xc208b761c0, 0xc20926dee0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:249 +0xf5e
github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)·fm(0x7f6a08d7c788, 0xc208b761c0, 0xc20926dee0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:95 +0x45
net/http.HandlerFunc.ServeHTTP(0xc2083d0cf0, 0x7f6a08d7c788, 0xc208b761c0, 0xc20926dee0)
        /usr/src/go/src/net [[Go-http-client/1.1] 10.0.100.160:44834]
I0606 18:31:30.041949    4435 handler.go:239] HTTP InternalServerError: Internal Error: unable to find Docker container "0e22d9be21827606e8a2759686d8016806178e9f6f84a952a4348ed202855f22"
I0606 18:31:30.042020    4435 server.go:1096] GET /stats/kube-system/filebeat-ip-10-0-61-117.ec2.internal/a5d1e2cc-1e6a-11e6-aed5-12bca96a847b/filebeat: (175.214µs) 500
goroutine 1094943 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc208b76380, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa6
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc208b76380, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x32
github.com/emicklei/go-restful.(*Response).WriteHeader(0xc208efad20, 0x1f4)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:191 +0x48
github.com/emicklei/go-restful.(*Response).WriteErrorString(0xc208efad20, 0x1f4, 0xc208e5db00, 0x72, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:180 +0x128
k8s.io/kubernetes/pkg/kubelet/server/stats.handleError(0xc208efad20, 0x7f6a08d4f040, 0xc208c55e00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/handler.go:240 +0x29a
k8s.io/kubernetes/pkg/kubelet/server/stats.(*handler).handlePodContainer(0xc2083c0d80, 0xc2090a9350, 0xc208efad20)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/handler.go:216 +0x8a6
k8s.io/kubernetes/pkg/kubelet/server/stats.*handler.(k8s.io/kubernetes/pkg/kubelet/server/stats.handlePodContainer)·fm(0xc2090a9350, 0xc208efad20)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/handler.go:72 +0x3b
github.com/emicklei/go-restful.(*Container).dispatch(0xc2083757a0, 0x7f6a08d7c788, 0xc208b76380, 0xc20926da00)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:249 +0xf5e
github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)·fm(0x7f6a08d7c788, 0xc208b76380, 0xc20926da00)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:95 +0x45
net/http.HandlerFunc.ServeHTTP(0xc2083d0cf0, 0x7f6a08d7c788, 0xc208b76380, 0xc20926da00)
        /usr/src/go/src/net [[Go-http-client/1.1] 10.0.100.160:44696]
I0606 18:31:30.042210    4435 handler.go:239] HTTP InternalServerError: Internal Error: unable to find Docker container "0bd3970bef992d28f9973355a541e23df70b03ac11176c351ffd1aa6c4db9837"
```

**Comment by DirectXMan12** [comment]
@dchen1107 do you have any ideas about what could cause this?

**Comment by ApsOps** [comment]
Looks like I'm hitting https://github.com/kubernetes/kubernetes/issues/18868. I'm on docker `v1.9.1` though.

**Comment by ApsOps** [comment]
Please note that restarting kubelet fixed these errors, at least for now.

**Comment by piosz** [comment]
This is problem was on Kubelet side and is fixed now. Please create issue in Kubernetes in case of more such problems.

**Comment by chowyu08** [comment]
@ApsOps I have teh same problem 
curl http://{{ MASTER }}/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/model/namespaces/default/pods/
 and restart kubelet,no use
