### ISSUE TITLE
Bug: can't get metrics for pods

### ISSUE THREAD

**Issue by lattwood** [kubernetes/heapster#1329]
I have no idea where to start debugging with this:

```
2016-10-06T20:45:55.606752531Z W1006 20:45:55.606509       1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces
2016-10-06T20:45:55.808089526Z W1006 20:45:55.807806       1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces
2016-10-06T20:45:55.908850591Z W1006 20:45:55.908579       1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces
2016-10-06T20:45:55.908906406Z I1006 20:45:55.908614       1 handlers.go:216] No metrics for pod staging/imposium-mysql-worker-2707898866-wkmxf
2016-10-06T20:45:55.908914789Z I1006 20:45:55.908623       1 handlers.go:216] No metrics for pod staging/imposium-mysql-worker-2707898866-8arod
2016-10-06T20:45:55.908952411Z I1006 20:45:55.908631       1 handlers.go:216] No metrics for pod staging/imposium-mysql-worker-2707898866-oll2v
2016-10-06T20:45:55.908957588Z I1006 20:45:55.908645       1 handlers.go:216] No metrics for pod staging/imposium-mysql-worker-2707898866-o0092
2016-10-06T20:45:56.107396692Z W1006 20:45:56.107141       1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces
2016-10-06T20:45:56.107420352Z I1006 20:45:56.107193       1 handlers.go:216] No metrics for pod staging/imposium-mysql-worker-2707898866-8arod
2016-10-06T20:45:56.107424575Z I1006 20:45:56.107200       1 handlers.go:216] No metrics for pod staging/imposium-mysql-worker-2707898866-wkmxf
2016-10-06T20:45:56.107428008Z I1006 20:45:56.107205       1 handlers.go:216] No metrics for pod staging/imposium-mysql-worker-2707898866-oll2v
2016-10-06T20:45:56.107431451Z I1006 20:45:56.107228       1 handlers.go:216] No metrics for pod staging/imposium-mysql-worker-2707898866-o0092
2016-10-06T20:45:56.307605740Z W1006 20:45:56.307309       1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces
2016-10-06T20:45:56.507424142Z W1006 20:45:56.507133       1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces
2016-10-06T20:45:56.607137364Z W1006 20:45:56.606879       1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces
2016-10-06T20:45:56.707212691Z W1006 20:45:56.706957       1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces
2016-10-06T20:45:56.707245740Z I1006 20:45:56.707013       1 handlers.go:216] No metrics for pod staging/imposium-mysql-worker-2707898866-wkmxf
2016-10-06T20:45:56.707250158Z I1006 20:45:56.707023       1 handlers.go:216] No metrics for pod staging/imposium-mysql-worker-2707898866-8arod
2016-10-06T20:45:56.707254249Z I1006 20:45:56.707030       1 handlers.go:216] No metrics for pod staging/imposium-mysql-worker-2707898866-oll2v
2016-10-06T20:45:56.707257358Z I1006 20:45:56.707047       1 handlers.go:216] No metrics for pod staging/imposium-mysql-worker-2707898866-o0092
2016-10-06T20:45:56.907078743Z W1006 20:45:56.906804       1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces
2016-10-06T20:45:57.107436115Z W1006 20:45:57.107165       1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces
2016-10-06T20:45:57.207732286Z W1006 20:45:57.207466       1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces
```

**Comment by lattwood** [comment]
This ends up filling the kubernetes HPA event log with these

```
  8m            17s             161     {horizontal-pod-autoscaler }                    Warning         FailedGetMetrics        failed to get CPU consumption and request: metrics obtained for 1/4 of pods (sample missing pod: staging/imposium-mysql-worker-2707898866-8arod)
  8m            17s             164     {horizontal-pod-autoscaler }                    Warning         FailedComputeReplicas   failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 1/4 of pods (sample missing pod: staging/imposium-mysql-worker-2707898866-8arod)
  7m            17s             61      {horizontal-pod-autoscaler }                    Warning         FailedGetMetrics        failed to get CPU consumption and request: metrics obtained for 1/4 of pods (sample missing pod: staging/imposium-mysql-worker-2707898866-wkmxf)
  7m            17s             59      {horizontal-pod-autoscaler }                    Warning         FailedComputeReplicas   failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 1/4 of pods (sample missing pod: staging/imposium-mysql-worker-2707898866-wkmxf)
  11m           1s              168     {horizontal-pod-autoscaler }                    Warning         FailedGetMetrics        failed to get CPU consumption and request: metrics obtained for 1/2 of pods (sample missing pod: staging/imposium-mysql-worker-2707898866-oll2v)
  11m           1s              168     {horizontal-pod-autoscaler }                    Warning         FailedComputeReplicas   failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 1/2 of pods (sample missing pod: staging/imposium-mysql-worker-2707898866-oll2v)
  43m           0s              111     {horizontal-pod-autoscaler }                    Warning         FailedComputeReplicas   (events with common reason combined)
  43m           0s              144     {horizontal-pod-autoscaler }                    Warning         FailedGetMetrics        (events with common reason combined)
```

**Comment by lattwood** [comment]
Here's the output when stacktraces are enabled for `listers.go:68`

```
W1007 14:16:03.358327       1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces
goroutine 306 [running]:
k8s.io/heapster/vendor/github.com/golang/glog.stacks(0x52fa700, 0x0, 0x0, 0x0)
        /go/src/k8s.io/heapster/vendor/github.com/golang/glog/glog.go:766 +0xb8
k8s.io/heapster/vendor/github.com/golang/glog.(*loggingT).output(0x52fa780, 0xc800000001, 0xc82084ee40, 0x518e695, 0xa, 0x44, 0x0)
        /go/src/k8s.io/heapster/vendor/github.com/golang/glog/glog.go:675 +0xcb
k8s.io/heapster/vendor/github.com/golang/glog.(*loggingT).printf(0x52fa780, 0x1, 0x3bfe5e0, 0x31, 0xc820d1f350, 0x1, 0x1)
        /go/src/k8s.io/heapster/vendor/github.com/golang/glog/glog.go:655 +0x1d4
k8s.io/heapster/vendor/github.com/golang/glog.Warningf(0x3bfe5e0, 0x31, 0xc820d1f350, 0x1, 0x1)
        /go/src/k8s.io/heapster/vendor/github.com/golang/glog/glog.go:1094 +0x5d
k8s.io/heapster/vendor/k8s.io/kubernetes/pkg/client/cache.ListAllByNamespace(0x7fcdceae1b08, 0xc820874a60, 0xc8208fec26, 0x7, 0x7fcdceb79140, 0xc821205060, 0xc820d1f4f8, 0x0, 0x0)
        /go/src/k8s.io/heapster/vendor/k8s.io/kubernetes/pkg/client/cache/listers.go:68 +0x401
k8s.io/heapster/vendor/k8s.io/kubernetes/pkg/client/cache.storePodsNamespacer.List(0x7fcdceae1b08, 0xc820874a60, 0xc8208fec26, 0x7, 0x7fcdceb79140, 0xc821205060, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/k8s.io/heapster/vendor/k8s.io/kubernetes/pkg/client/cache/listers_core.go:62 +0xcb
k8s.io/heapster/metrics/apis/metrics.podMetricsInNamespaceList(0xc820351800, 0xc820fcaae0, 0xc8208fed80, 0xc8208fec26, 0x7)
        /go/src/k8s.io/heapster/metrics/apis/metrics/handlers.go:203 +0x464
k8s.io/heapster/metrics/apis/metrics.(*Api).podMetricsList(0xc820351800, 0xc820fcaae0, 0xc8208fed80)
        /go/src/k8s.io/heapster/metrics/apis/metrics/handlers.go:189 +0xb5
k8s.io/heapster/metrics/apis/metrics.(*Api).(k8s.io/heapster/metrics/apis/metrics.podMetricsList)-fm(0xc820fcaae0, 0xc8208fed80)
        /go/src/k8s.io/heapster/metrics/apis/metrics/handlers.go:78 +0x34
k8s.io/heapster/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc8204e25a0, 0x7fcdceb242d0, 0xc82022ab60, 0xc820e0e620)
        /go/src/k8s.io/heapster/vendor/github.com/emicklei/go-restful/container.go:272 +0xf30
k8s.io/heapster/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/heapster/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x7fcdceb242d0, 0xc82022ab60, 0xc820e0e620)
        /go/src/k8s.io/heapster/vendor/github.com/emicklei/go-restful/container.go:120 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc820221c50, 0x7fcdceb242d0, 0xc82022ab60, 0xc820e0e620)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc82020be30, 0x7fcdceb242d0, 0xc82022ab60, 0xc820e0e620)
        /usr/local/go/src/net/http/server.go:1910 +0x17d
k8s.io/heapster/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc8204e25a0, 0x7fcdceb242d0, 0xc82022ab60, 0xc820e0e620)
        /go/src/k8s.io/heapster/vendor/github.com/emicklei/go-restful/container.go:287 +0x43
net/http.(*ServeMux).ServeHTTP(0xc82020b170, 0x7fcdceb242d0, 0xc82022ab60, 0xc820e0e620)
        /usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc8201de900, 0x7fcdceb242d0, 0xc82022ab60, 0xc820e0e620)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82016aa00)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e
```

**Comment by piosz** [comment]
Which version of Heapster and Kubernetes do you use?

**Comment by jbmcg** [comment]
Heapster 1.2.0 and Kubernetes 1.4.0

**Comment by agsola** [comment]
I reply in here because my problem may be related to this one.

I have installed Heapster using this guide:
https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md

However, after installing it I CAN see the metrics from my pods without any problem in the UI.

I'm getting this error:
~# kubectl describe hpa/my-nginx 
Name:				my-nginx
Namespace:			default
Labels:				<none>
Annotations:			<none>
CreationTimestamp:		Wed, 12 Oct 2016 10:21:12 +0200
Reference:			Deployment/my-nginx
Target CPU utilization:		50%
Current CPU utilization:	<unset>
Min replicas:			1
Max replicas:			10
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  12m		11m		4	{horizontal-pod-autoscaler }			Warning		FailedGetMetrics	failed to get CPU consumption and request: some pods do not have request for cpu
  12m		11m		4	{horizontal-pod-autoscaler }			Warning		FailedComputeReplicas	failed to get CPU utilization: failed to get CPU consumption and request: some pods do not have request for cpu
  9m		3m		13	{horizontal-pod-autoscaler }			Warning		FailedGetMetrics	failed to get CPU consumption and request: some pods do not have request for cpu
  9m		3m		13	{horizontal-pod-autoscaler }			Warning		FailedComputeReplicas	failed to get CPU utilization: failed to get CPU consumption and request: some pods do not have request for cpu
  2m		9s		5	{horizontal-pod-autoscaler }			Warning		FailedGetMetrics	failed to get CPU consumption and request: some pods do not have request for cpu
  2m		9s		5	{horizontal-pod-autoscaler }			Warning		FailedComputeReplicas	failed to get CPU utilization: failed to get CPU consumption and request: some pods do not have request for cpu


There is no way I can get the stats from the hpa, 
With get, the same:
~# kubectl get hpa/my-nginx 
NAME       REFERENCE             TARGET    CURRENT     MINPODS   MAXPODS   AGE
my-nginx   Deployment/my-nginx   50%       <waiting>   1         10        13m

No matter how much time I wait...
It is always at "waiting", though I can get the stats from the UI.

**Comment by lattwood** [comment]
@piosz FYI, @jbmcg will be following up on this with you, I believe he's also on the k8s Slack

**Comment by jbmcg** [comment]
As of right now, there's no longer anything in the heapster logs about Object interfaces or anything anymore, its just a hard "No metrics for pod namespace/pod-name" over and over again for every pod that is in a HPA (total of 3 HPAs, 1 using CPU usage, 2 using a custom metric which is a prometheus gauge between 0 and 1). Also, if I put load on one of the pods, I can usually get a "No metrics for container container-name in pod namespace/pod-name" message vs. the usual one.

I'm able to see all metrics properly in cAdvisor (including the custom ones) and I can see graphs in Grafana for the pods that heapster is saying that it can't get metrics for, so it would appear the metrics are getting stored properly (although the graphs do look a little unusually flat)

I switched the sink to "log" and can see that its definitely getting metrics for a number of things consistently, just not metrics for pods under HPAs it would seem.

**Comment by agsola** [comment]
I've been able to get it working, just setting the CPU request.

**Comment by jbmcg** [comment]
The HPA that uses CPU usage is actually working properly now, its just the custom metrics (or the HPAs that use custom metrics) that are failing.

```  
3h		1s		13844	{horizontal-pod-autoscaler }			Warning		FailedGetCustomMetrics	metrics obtained for 1/2 of pods (sample missing pod: staging/imposium-sqs-worker-684296566-5l3a4)
3h		1s		13844	{horizontal-pod-autoscaler }			Warning		FailedComputeCMReplicas	failed to get custom metric value: metrics obtained for 1/2 of pods (sample missing pod: staging/imposium-sqs-worker-684296566-5l3a4)
```

**Comment by piosz** [comment]
Custom metrics feature is in alpha state and is going to be removed soon. There is a new version of it in progress. @DirectXMan12 is driving the effort. You can see a proposal here https://github.com/kubernetes/kubernetes/pull/34754

@mwielgus @jszczepkowski FYI the current implementation of HPA with custom metrics seems to not work correctly.

Closing the issues since you resolved the problem (excepts from custom metrics). If you need more help please create an issue on Kubernetes or use slack.

**Comment by jbmcg** [comment]
FWIW I believe we actually have it working now. I think the main source of our woes was actually due to security group rules - we had to open up the ports we were using for InfluxDB and metrics collection on the Kubernetes worker nodes for when a pod is scheduled on a different instance than heapster is scheduled on.

**Comment by patagona-afriemann** [comment]
We are pretty much having the same Issue. We had deployments configured with resource limits+requests and did not get any metrics with the heapster logs in the OP.

Removing the limits actually got us metrics, though heapster is still logging `No metrics for pod` every few minutes. The HPA is working now, however removing the limits seems wrong to me.
