### ISSUE TITLE
[v1.2.0]heapster crash when get version

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/heapster#1370]
```
[root@ip-172-18-6-200 heapster]# git checkout v1.2.0
HEAD is now at eea8c96... Merge pull request #1291 from piosz/rel-1.2
[root@ip-172-18-6-200 heapster]# git branch
* (detached from v1.2.0)
  master
[root@ip-172-18-6-200 heapster]# make
...
[root@ip-172-18-6-200 heapster]# ./heapster version
F1107 04:26:47.195087   15124 heapster.go:77] Wrong number of sources specified
goroutine 1 [running]:
k8s.io/heapster/vendor/github.com/golang/glog.stacks(0x3549e00, 0x0, 0x0, 0x0)
	/data/src/k8s.io/heapster/vendor/github.com/golang/glog/glog.go:766 +0xb8
k8s.io/heapster/vendor/github.com/golang/glog.(*loggingT).output(0x3529b00, 0xc800000003, 0xc8200b6300, 0x34f5662, 0xb, 0x4d, 0x0)
	/data/src/k8s.io/heapster/vendor/github.com/golang/glog/glog.go:717 +0x259
k8s.io/heapster/vendor/github.com/golang/glog.(*loggingT).printDepth(0x3529b00, 0x3, 0x1, 0xc8204b7d90, 0x1, 0x1)
	/data/src/k8s.io/heapster/vendor/github.com/golang/glog/glog.go:646 +0x1b8
k8s.io/heapster/vendor/github.com/golang/glog.(*loggingT).print(0x3529b00, 0x3, 0xc8204b7d90, 0x1, 0x1)
	/data/src/k8s.io/heapster/vendor/github.com/golang/glog/glog.go:637 +0x50
k8s.io/heapster/vendor/github.com/golang/glog.Fatal(0xc8204b7d90, 0x1, 0x1)
	/data/src/k8s.io/heapster/vendor/github.com/golang/glog/glog.go:1125 +0x49
main.main()
	/data/src/k8s.io/heapster/metrics/heapster.go:77 +0x48f
```

**Comment by mdshuai** [comment]
Master branch works correctly.
[root@ip-172-18-6-200 heapster]# ./heapster version
I1107 04:34:24.818192   18164 heapster.go:65] ./heapster version
I1107 04:34:24.818241   18164 heapster.go:66] Heapster version 1.2.0
F1107 04:34:24.818248   18164 heapster.go:73] Failed to get kubernetes address: No kubernetes source found.

**Comment by mdshuai** [comment]
@DirectXMan12 @mwringe

**Comment by mwringe** [comment]
There is no 'heapster version' command. Heapster always prints out the version as part of its startup, and as you can see in both casese it ends in an error. All that has changed between 1.2.0 and master is the error message.

**Comment by piosz** [comment]
Closing as WAI (see @mwringe comment).
