### ISSUE TITLE
panic: runtime error: slice bounds out of range. It's a bug?

### ISSUE THREAD

**Issue by xwisen** [kubernetes/heapster#1388]
> [root@agent1 ~]# ./heapster --source="kubernetes:http://20.26.2.110:18080?insecure=true&inClusterConfig=false&useServiceAccount=false&auth=" --sink=log --v=6 --logtostderr=true 
I1118 09:54:33.225219   18622 heapster.go:69] ./heapster --source=kubernetes:http://20.26.2.110:18080?insecure=true&inClusterConfig=false&useServiceAccount=false&auth= --sink=log --v=6 --logtostderr=true
I1118 09:54:33.225471   18622 heapster.go:70] Heapster version 1.2.0
I1118 09:54:33.225619   18622 configs.go:60] Using Kubernetes client with master "http://20.26.2.110:18080" and version v1
I1118 09:54:33.225667   18622 configs.go:61] Using kubelet port 10255
I1118 09:54:33.243952   18622 round_trippers.go:318] GET http://20.26.2.110:18080/api/v1/nodes 200 OK in 16 milliseconds
I1118 09:54:33.255969   18622 reflector.go:200] Starting reflector *api.Node (1h0m0s) from k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339
I1118 09:54:33.256260   18622 heapster.go:99] Starting with Log Sink
I1118 09:54:33.256295   18622 heapster.go:99] Starting with Metric Sink
I1118 09:54:33.256949   18622 reflector.go:249] Listing and watching *api.Node from k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339
I1118 09:54:33.257631   18622 reflector.go:200] Starting reflector *api.Pod (1h0m0s) from k8s.io/heapster/metrics/heapster.go:272
I1118 09:54:33.257738   18622 reflector.go:200] Starting reflector *api.Node (1h0m0s) from k8s.io/heapster/metrics/heapster.go:280
I1118 09:54:33.258589   18622 reflector.go:200] Starting reflector *api.Namespace (1h0m0s) from k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84
I1118 09:54:33.259410   18622 reflector.go:200] Starting reflector *api.Node (1h0m0s) from k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:96
I1118 09:54:33.260411   18622 reflector.go:249] Listing and watching *api.Namespace from k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84
I1118 09:54:33.260447   18622 reflector.go:249] Listing and watching *api.Node from k8s.io/heapster/metrics/heapster.go:280
I1118 09:54:33.261509   18622 reflector.go:249] Listing and watching *api.Node from k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:96
I1118 09:54:33.261741   18622 reflector.go:249] Listing and watching *api.Pod from k8s.io/heapster/metrics/heapster.go:272
I1118 09:54:33.273376   18622 round_trippers.go:318] GET http://20.26.2.110:18080/api/v1/nodes?resourceVersion=0 200 OK in 15 milliseconds
I1118 09:54:33.281754   18622 round_trippers.go:318] GET http://20.26.2.110:18080/api/v1/nodes?resourceVersion=0 200 OK in 18 milliseconds
I1118 09:54:33.282358   18622 round_trippers.go:318] GET http://20.26.2.110:18080/api/v1/namespaces?resourceVersion=0 200 OK in 21 milliseconds
I1118 09:54:33.285280   18622 round_trippers.go:318] GET http://20.26.2.110:18080/api/v1/nodes?resourceVersion=0 200 OK in 24 milliseconds
I1118 09:54:33.293460   18622 round_trippers.go:318] GET http://20.26.2.110:18080/api/v1/pods?resourceVersion=0 200 OK in 30 milliseconds
I1118 09:54:33.332493   18622 heapster.go:189] Starting heapster on port 8082
I1118 09:54:33.494521   18622 round_trippers.go:318] GET http://20.26.2.110:18080/api/v1/watch/namespaces?resourceVersion=2580409&timeoutSeconds=481 200 OK in 209 milliseconds
I1118 09:54:33.524205   18622 round_trippers.go:318] GET http://20.26.2.110:18080/api/v1/watch/nodes?resourceVersion=2703457&timeoutSeconds=582 200 OK in 205 milliseconds
I1118 09:54:33.533347   18622 round_trippers.go:318] GET http://20.26.2.110:18080/api/v1/watch/nodes?resourceVersion=2703457&timeoutSeconds=499 200 OK in 207 milliseconds
I1118 09:54:33.536310   18622 round_trippers.go:318] GET http://20.26.2.110:18080/api/v1/watch/nodes?resourceVersion=2703457&timeoutSeconds=431 200 OK in 204 milliseconds
I1118 09:54:33.561053   18622 round_trippers.go:318] GET http://20.26.2.110:18080/api/v1/watch/pods?resourceVersion=2596239&timeoutSeconds=427 200 OK in 205 milliseconds
I1118 09:55:03.293070   18622 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I1118 09:55:03.293230   18622 reflector.go:403] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Watch close - *api.Namespace total 0 items received
I1118 09:55:03.360727   18622 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I1118 09:55:03.360954   18622 reflector.go:403] k8s.io/heapster/metrics/heapster.go:272: Watch close - *api.Pod total 0 items received
I1118 09:55:03.510972   18622 round_trippers.go:318] GET http://20.26.2.110:18080/api/v1/watch/namespaces?resourceVersion=2580409&timeoutSeconds=506 200 OK in 217 milliseconds
I1118 09:55:03.573627   18622 round_trippers.go:318] GET http://20.26.2.110:18080/api/v1/watch/pods?resourceVersion=2596239&timeoutSeconds=319 200 OK in 212 milliseconds
I1118 09:55:05.000627   18622 manager.go:79] Scraping metrics start: 2016-11-18 09:54:00 +0800 CST, end: 2016-11-18 09:55:00 +0800 CST
I1118 09:55:05.019716   18622 manager.go:98] Querying source: kubelet:20.26.20.156:10255
I1118 09:55:05.032727   18622 manager.go:98] Querying source: kubelet:20.26.2.54:10255
I1118 09:55:05.037616   18622 manager.go:98] Querying source: kubelet:20.26.2.52:10255
I1118 09:55:05.039751   18622 manager.go:98] Querying source: kubelet:20.26.2.53:10255
I1118 09:55:05.042536   18622 manager.go:98] Querying source: kubelet:20.26.2.51:10255
I1118 09:55:05.046588   18622 manager.go:98] Querying source: kubelet:20.26.20.157:10255
I1118 09:55:05.108382   18622 round_trippers.go:318] POST http://20.26.2.53:10255/stats/container/ 200 OK in 67 milliseconds
I1118 09:55:05.109039   18622 round_trippers.go:318] POST http://20.26.20.156:10255/stats/container/ 200 OK in 88 milliseconds
I1118 09:55:05.130145   18622 round_trippers.go:318] POST http://20.26.20.157:10255/stats/container/ 200 OK in 82 milliseconds
I1118 09:55:05.262634   18622 kubelet.go:232] successfully obtained stats for 92 containers
panic: runtime error: slice bounds out of range

goroutine 128 [running]:
panic(0x2296140, 0xc8200100b0)
	/usr/local/google/home/pszczesniak/.gvm/gos/go1.6.3/src/runtime/panic.go:481 +0x3e6
k8s.io/heapster/metrics/sources/kubelet.(*kubeletMetricsSource).decodeMetrics(0xc820414ba0, 0xc82029da40, 0x0, 0x0, 0xc820898240)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sources/kubelet/kubelet.go:161 +0x18ca
k8s.io/heapster/metrics/sources/kubelet.(*kubeletMetricsSource).ScrapeMetrics(0xc820414ba0, 0xecfc05638, 0xc800000000, 0x35356c0, 0xecfc05674, 0xc800000000, 0x35356c0, 0xc820238000)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sources/kubelet/kubelet.go:240 +0x4ec
k8s.io/heapster/metrics/sources.scrape(0x7fc5f5d8c530, 0xc820414ba0, 0xecfc05638, 0xc800000000, 0x35356c0, 0xecfc05674, 0xc800000000, 0x35356c0, 0x0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sources/manager.go:169 +0x328
k8s.io/heapster/metrics/sources.(*sourceManager).ScrapeMetrics.func1(0xc820a65200, 0x7fc5f5d8c530, 0xc820414ba0, 0xc820414d20, 0xecfc05638, 0x7fc500000000, 0x35356c0, 0xecfc05674, 0x0, 0x35356c0, ...)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sources/manager.go:99 +0x1a9
created by k8s.io/heapster/metrics/sources.(*sourceManager).ScrapeMetrics
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sources/manager.go:115 +0x512

**Comment by xwisen** [comment]
kubernetes version:
[root@master1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by xwisen** [comment]
Maybe a container named `reg.5000` caused this problem.The cAdvisor disdinguish containers by `.`.
