### ISSUE TITLE
Heapster container crashing v1.2.0 continuously

### ISSUE THREAD

**Issue by phagunbaya** [kubernetes/heapster#1837]
Kubernetes version: v1.5.3

Logs :
```
Oct 2 06:37:03 heapster-v1.2.0-1448994189-8c5qs heapster  E1002 13:37:03.876291       1 summary.go:390] Node k8s-master-a00b044c-0 is not ready
Oct 2 06:38:03 heapster-v1.2.0-1448994189-8c5qs heapster  E1002 13:38:03.874926       1 summary.go:390] Node k8s-master-a00b044c-0 is not ready
Oct 4 14:50:05 heapster-v1.2.0-1448994189-8c5qs heapster error panic: runtime error: index out of range
Oct 4 14:50:05 heapster-v1.2.0-1448994189-8c5qs heapster
Oct 4 14:50:05 heapster-v1.2.0-1448994189-8c5qs heapster  goroutine 342470 [running]:
Oct 4 14:50:05 heapster-v1.2.0-1448994189-8c5qs heapster  panic(0x2296140, 0xc820014010)
Oct 4 14:50:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/.gvm/gos/go1.6.3/src/runtime/panic.go:481 +0x3e6
Oct 4 14:50:05 heapster-v1.2.0-1448994189-8c5qs heapster  k8s.io/heapster/metrics/sources.(*sourceManager).ScrapeMetrics(0xc82029d080, 0xed1674e4c, 0xc800000000, 0x35356c0, 0xed1674e88, 0xc800000000, 0x35356c0, 0xc8210347c0)
Oct 4 14:50:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sources/manager.go:144 +0x101c
Oct 4 14:50:05 heapster-v1.2.0-1448994189-8c5qs heapster  k8s.io/heapster/metrics/manager.(*realManager).housekeep.func1(0xed1674e4c, 0x0, 0x35356c0, 0xed1674e88, 0x0, 0x35356c0, 0xc820065e00)
Oct 4 14:50:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/manager/manager.go:128 +0xca
Oct 4 14:50:05 heapster-v1.2.0-1448994189-8c5qs heapster  created by k8s.io/heapster/metrics/manager.(*realManager).housekeep
Oct 4 14:50:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/manager/manager.go:143 +0x33e
Oct 4 14:51:05 heapster-v1.2.0-1448994189-8c5qs heapster error panic: runtime error: index out of range
Oct 4 14:51:05 heapster-v1.2.0-1448994189-8c5qs heapster
Oct 4 14:51:05 heapster-v1.2.0-1448994189-8c5qs heapster  goroutine 40 [running]:
Oct 4 14:51:05 heapster-v1.2.0-1448994189-8c5qs heapster  panic(0x2296140, 0xc820014010)
Oct 4 14:51:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/.gvm/gos/go1.6.3/src/runtime/panic.go:481 +0x3e6
Oct 4 14:51:05 heapster-v1.2.0-1448994189-8c5qs heapster  k8s.io/heapster/metrics/sources.(*sourceManager).ScrapeMetrics(0xc8202ae8c0, 0xed1674e88, 0xc800000000, 0x35356c0, 0xed1674ec4, 0x0, 0x35356c0, 0x0)
Oct 4 14:51:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sources/manager.go:144 +0x101c
Oct 4 14:51:05 heapster-v1.2.0-1448994189-8c5qs heapster  k8s.io/heapster/metrics/manager.(*realManager).housekeep.func1(0xed1674e88, 0x0, 0x35356c0, 0xed1674ec4, 0x0, 0x35356c0, 0xc82007de00)
Oct 4 14:51:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/manager/manager.go:128 +0xca
Oct 4 14:51:05 heapster-v1.2.0-1448994189-8c5qs heapster  created by k8s.io/heapster/metrics/manager.(*realManager).housekeep
Oct 4 14:51:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/manager/manager.go:143 +0x33e
Oct 4 14:52:05 heapster-v1.2.0-1448994189-8c5qs heapster error panic: runtime error: index out of range
Oct 4 14:52:05 heapster-v1.2.0-1448994189-8c5qs heapster
Oct 4 14:52:05 heapster-v1.2.0-1448994189-8c5qs heapster  goroutine 241 [running]:
Oct 4 14:52:05 heapster-v1.2.0-1448994189-8c5qs heapster  panic(0x2296140, 0xc820014010)
Oct 4 14:52:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/.gvm/gos/go1.6.3/src/runtime/panic.go:481 +0x3e6
Oct 4 14:52:05 heapster-v1.2.0-1448994189-8c5qs heapster  k8s.io/heapster/metrics/sources.(*sourceManager).ScrapeMetrics(0xc82028d300, 0xed1674ec4, 0xc800000000, 0x35356c0, 0xed1674f00, 0x0, 0x35356c0, 0x0)
Oct 4 14:52:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sources/manager.go:144 +0x101c
Oct 4 14:52:05 heapster-v1.2.0-1448994189-8c5qs heapster  k8s.io/heapster/metrics/manager.(*realManager).housekeep.func1(0xed1674ec4, 0x0, 0x35356c0, 0xed1674f00, 0x0, 0x35356c0, 0xc82045c0c0)
Oct 4 14:52:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/manager/manager.go:128 +0xca
Oct 4 14:52:05 heapster-v1.2.0-1448994189-8c5qs heapster  created by k8s.io/heapster/metrics/manager.(*realManager).housekeep
Oct 4 14:52:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/manager/manager.go:143 +0x33e
Oct 4 14:55:05 heapster-v1.2.0-1448994189-8c5qs heapster error panic: runtime error: index out of range
Oct 4 14:55:05 heapster-v1.2.0-1448994189-8c5qs heapster
Oct 4 14:55:05 heapster-v1.2.0-1448994189-8c5qs heapster  goroutine 263 [running]:
Oct 4 14:55:05 heapster-v1.2.0-1448994189-8c5qs heapster  panic(0x2296140, 0xc820014010)
Oct 4 14:55:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/.gvm/gos/go1.6.3/src/runtime/panic.go:481 +0x3e6
Oct 4 14:55:05 heapster-v1.2.0-1448994189-8c5qs heapster  k8s.io/heapster/metrics/sources.(*sourceManager).ScrapeMetrics(0xc8202c71a0, 0xed1674f78, 0xc800000000, 0x35356c0, 0xed1674fb4, 0xc800000000, 0x35356c0, 0xc8202a0630)
Oct 4 14:55:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sources/manager.go:144 +0x101c
Oct 4 14:55:05 heapster-v1.2.0-1448994189-8c5qs heapster  k8s.io/heapster/metrics/manager.(*realManager).housekeep.func1(0xed1674f78, 0x0, 0x35356c0, 0xed1674fb4, 0x0, 0x35356c0, 0xc820065e60)
Oct 4 14:55:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/manager/manager.go:128 +0xca
Oct 4 14:55:05 heapster-v1.2.0-1448994189-8c5qs heapster  created by k8s.io/heapster/metrics/manager.(*realManager).housekeep
Oct 4 14:55:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/manager/manager.go:143 +0x33e
Oct 5 09:30:05 heapster-v1.2.0-1448994189-8c5qs heapster error panic: runtime error: index out of range
Oct 5 09:30:05 heapster-v1.2.0-1448994189-8c5qs heapster
Oct 5 09:30:05 heapster-v1.2.0-1448994189-8c5qs heapster  goroutine 12688 [running]:
Oct 5 09:30:05 heapster-v1.2.0-1448994189-8c5qs heapster  panic(0x2296140, 0xc820014010)
Oct 5 09:30:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/.gvm/gos/go1.6.3/src/runtime/panic.go:481 +0x3e6
Oct 5 09:30:05 heapster-v1.2.0-1448994189-8c5qs heapster  k8s.io/heapster/metrics/sources.(*sourceManager).ScrapeMetrics(0xc8202bb100, 0xed16854cc, 0xc800000000, 0x35356c0, 0xed1685508, 0x0, 0x35356c0, 0xed168550e)
Oct 5 09:30:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sources/manager.go:144 +0x101c
Oct 5 09:30:05 heapster-v1.2.0-1448994189-8c5qs heapster  k8s.io/heapster/metrics/manager.(*realManager).housekeep.func1(0xed16854cc, 0x0, 0x35356c0, 0xed1685508, 0x0, 0x35356c0, 0xc820494060)
Oct 5 09:30:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/manager/manager.go:128 +0xca
Oct 5 09:30:05 heapster-v1.2.0-1448994189-8c5qs heapster  created by k8s.io/heapster/metrics/manager.(*realManager).housekeep
Oct 5 09:30:05 heapster-v1.2.0-1448994189-8c5qs heapster  	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/manager/manager.go:143 +0x33e
```

I dont see any issue with node `k8s-master-a00b044c-0`. Other pods are running all fine.

**Comment by DirectXMan12** [comment]
Can you please try with the latest version, so that we can determine if it's still an issue?  Looking at the relevant code, it looks like the only way it could panic is if the amount of time taken is less than zero, which should never happen unless times are changing inconsistently on your cluster
