### ISSUE TITLE
Unable to authorize on Kubelet SSL Endpoint

### ISSUE THREAD

**Issue by PheonixS** [kubernetes/heapster#1962]
heapster deployment part:
           
```
"name": "heapster",
"image": "k8s.gcr.io/heapster:v1.5.1",
"command": [
"/heapster",
"--source=kubernetes.summary_api:https://10.10.8.118:6443?insecure=true&useServiceAccount=true&kubeletPort=10250&kubeletHttps=true"
```

Kubelet configured to deny anonymous access.
10.10.8.118 is point of 10-10-8-118.kubernetes.default.svc.cluster.local. 

Also X509 auth enabled on Kubelet. 
What I need to configure on Heapster?

Logs:
```
I0222 14:32:00.429926       1 heapster.go:79] Heapster version v1.5.1
I0222 14:32:00.430077       1 configs.go:61] Using Kubernetes client with master "https://10.10.8.118:6443" and version v1
I0222 14:32:00.430087       1 configs.go:62] Using kubelet port 10250
I0222 14:32:00.430279       1 heapster.go:202] Starting with Metric Sink
I0222 14:32:00.532446       1 heapster.go:112] Starting heapster on port 8082
E0222 14:33:05.025300       1 manager.go:101] Error in scraping containers from kubelet_summary:10.10.10.130:10250: request failed - "401 Unauthorized", response: "Unauthorized"
E0222 14:33:05.025432       1 manager.go:101] Error in scraping containers from kubelet_summary:10.10.8.118:10250: request failed - "401 Unauthorized", response: "Unauthorized"
E0222 14:33:05.031547       1 manager.go:101] Error in scraping containers from kubelet_summary:10.10.8.119:10250: request failed - "401 Unauthorized", response: "Unauthorized"
E0222 14:33:05.033999       1 manager.go:101] Error in scraping containers from kubelet_summary:10.10.8.120:10250: request failed - "401 Unauthorized", response: "Unauthorized"
E0222 14:33:05.044359       1 manager.go:101] Error in scraping containers from kubelet_summary:10.10.11.13:10250: request failed - "401 Unauthorized", response: "Unauthorized"
W0222 14:33:25.000529       1 manager.go:152] Failed to get all responses in time (got 0/5)
```

Also logs from kubelet:
```
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: I0222 18:18:05.127194   25476 server.go:796] GET /stats/summary/: (149.223µs) 401
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: goroutine 2151585 [running]:
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc42089c380, 0x191)
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc42089c380, 0x191)
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteHeader(0xc4213c84e0, 0x191)
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:201 +0x41
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteErrorString(0xc4213c84e0, 0x191, 0x497381e, 0xc, 0x0, 0x0)
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:181 +0x46
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: k8s.io/kubernetes/pkg/kubelet/server.(*Server).InstallAuthFilter.func1(0xc4213d4450, 0xc4213c84e0, 0xc4213d44e0)
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:231 +0x7fb
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc4213d44e0, 0xc4213d4450, 0xc4213c84e0)
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/filter.go:19 +0x68
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc420ebf200, 0xa669a80, 0xc42089c380, 0xc4221d6000)
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:274 +0x8ff
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0xa669a80, 0xc42089c380, 0xc4221d6000)
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x48
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: net/http.HandlerFunc.ServeHTTP(0xc420711fb0, 0xa669a80, 0xc42089c380, 0xc4221d6000)
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]:         /usr/local/go/src/net/http/server.go:1918 +0x44
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: net/http.(*ServeMux).ServeHTTP(0xc421279470, 0xa669a80, 0xc42089c380, 0xc4221d6000)
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]:         /usr/local/go/src/net/http/server.go:2254 +0x130
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc420ebf200, 0xa669a80, 0xc42089c380, 0xc4221d6000)
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:292 +0x4d
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: k8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc4209bd090, 0xa669a80, 0xc42089c380, 0xc4221d6000)
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:795 +0x106
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: net/http.serverHandler.ServeHTTP(0xc42065e000, 0xa66af80, 0xc421ae8000, 0xc4221d6000)
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]:         /usr/local/go/src/net/http/server.go:2619 +0xb4
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: net/http.(*conn).serve(0xc4229f8140, 0xa66e7c0, 0xc421d06140)
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]:         /usr/local/go/src/net/http/server.go:1801 +0x71d
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: created by net/http.(*Server).Serve
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]:         /usr/local/go/src/net/http/server.go:2720 +0x288
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]: logging error output: "Unauthorized"
Feb 22 18:18:05 xen-kub-master1 kubelet[25476]:  [[Go-http-client/1.1] 10.10.9.182:53090]
```

**Comment by DirectXMan12** [comment]
It will attempt to authenticate with Kubelet the same way it authenticates with the Kubernetes master: https://github.com/kubernetes/heapster/blob/b0a73e1c64a2787242368b55efdb542a632ef726/metrics/sources/kubelet/configs.go#L67, so make sure that you've set up Kubelet to accept similar auth.

**Comment by DirectXMan12** [comment]
It will attempt to authenticate with Kubelet the same way it authenticates with the Kubernetes API server: https://github.com/kubernetes/heapster/blob/b0a73e1c64a2787242368b55efdb542a632ef726/metrics/sources/kubelet/configs.go#L67, so make sure that you've set up Kubelet to accept similar auth.

**Comment by PheonixS** [comment]
We solve the issue by adding
`--authentication-token-webhook=true \`
in file` /etc/kubernetes/kubelet.env` And after this restarting all kubelets in cluster.
