### ISSUE TITLE
panic in integration tests

### ISSUE THREAD

**Issue by piosz** [kubernetes/heapster#871]
godep go test -v --timeout=30m ./integration/... --vmodule=*=2  --namespace=heapster-e2e-tests --kube_versions="1.0.6"
=== RUN   TestHeapster
I0111 10:26:56.884810   25208 framework.go:257] Disabled cluster monitoring
--- FAIL: TestHeapster (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x48a9df]

goroutine 24 [running]:
testing.tRunner.func1(0xc82017ecf0)
	/usr/local/go/src/testing/testing.go:450 +0x171
k8s.io/heapster/integration.getKubeClient(0x0, 0x0, 0x4b, 0x0, 0x0)
	/home/jenkins/workspace/project/src/k8s.io/heapster/integration/framework.go:205 +0x67f
k8s.io/heapster/integration.requireNewCluster(0xc8202293e0, 0x23, 0x7ffec3d0b615, 0x5, 0xc82023a960)
	/home/jenkins/workspace/project/src/k8s.io/heapster/integration/framework.go:220 +0x24
k8s.io/heapster/integration.downloadAndSetupCluster(0x7ffec3d0b615, 0x5, 0x0, 0x0, 0x0, 0x0)
	/home/jenkins/workspace/project/src/k8s.io/heapster/integration/framework.go:258 +0x989
k8s.io/heapster/integration.newKubeFramework(0x7ffec3d0b615, 0x5, 0x0, 0x0, 0x0, 0x0)
	/home/jenkins/workspace/project/src/k8s.io/heapster/integration/framework.go:295 +0x20a
k8s.io/heapster/integration.apiTest(0x7ffec3d0b615, 0x5, 0x11ddad0, 0xd, 0x0, 0x0)
	/home/jenkins/workspace/project/src/k8s.io/heapster/integration/heapster_api_test.go:563 +0x52
k8s.io/heapster/integration.runApiTest(0x0, 0x0)
	/home/jenkins/workspace/project/src/k8s.io/heapster/integration/heapster_api_test.go:653 +0x230
k8s.io/heapster/integration.TestHeapster(0xc82017ecf0)
	/home/jenkins/workspace/project/src/k8s.io/heapster/integration/heapster_api_test.go:664 +0x140
testing.tRunner(0xc82017ecf0, 0x198f150)
	/usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0x13d72f0, 0x198f150, 0x1, 0x1, 0x7f510a6ed901)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc8200a3ee8, 0x30)
	/usr/local/go/src/testing/testing.go:494 +0x70
main.main()
	k8s.io/heapster/integration/_test/_testmain.go:54 +0x116

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x19b3220)
	/home/jenkins/workspace/project/src/k8s.io/heapster/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
created by github.com/golang/glog.init.1
	/home/jenkins/workspace/project/src/k8s.io/heapster/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297
exit status 2
FAIL	k8s.io/heapster/integration	0.013s

**Comment by piosz** [comment]
The issue is fixed.
